name: Publish

on:
  workflow_run:
    workflows: ["Automated Tests"]
    types:
      - completed
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

permissions:
  contents: write
  checks: read
  issues: read
  packages: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
